version: "3"

services:
  nginx:
    image: nginx
    depends_on:
      - app
    restart: unless-stopped
    volumes:
      - ./dist:/usr/share/nginx/html:ro

  app:
    image: node:12
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "yarn install &&yarn build && sleep 365d"