version: "3"

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - app
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8085:80

  app:
    image: node:12
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "yarn install && yarn build && sleep 365d"